sudo: false
language: node_js
node_js:
- "12.8.1"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
    - libavutil-dev
os:
- osx
- linux
- windows
env:
- YARN_GPG=no # otherwise windows build hangs
before_install:
  - if [ $TRAVIS_OS_NAME = windows ]; then cinst -y python2; fi
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- yarn prebuild
- if [ $TRAVIS_OS_NAME = windows ]; then yarn prebuild-ia32; fi
- if [ $TRAVIS_OS_NAME = osx ]; then cp "$TRAVIS_BUILD_DIR/lib/libavutil.dylib" "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/";
  install_name_tool -change "/usr/local/lib/libavutil.56.dylib" "@loader_path/libavutil.dylib" "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/node-napi.node";
  otool -L "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/node-napi.node";
  install_name_tool -change "/usr/local/lib/libavutil.56.dylib" "@loader_path/libavutil.dylib" "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/electron-napi.node";
  otool -L "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/electron-napi.node";
  fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: 12
  api_key:
    secure: JYnCgKm2thPygQUOlWwJDk2W7S65pXTrziiqojGledO3wYBmV2rfeYy/88IuV3jXqoKes3mlVhhs8Dbk6mrbDyiSlS9eCWopDSJBUp7DsiL5jXtH5DVgP+pvNr3/Rv/pHzeSVD09FYlkShnGvb8+urRv97kZ/R4nE8jlCaCq0MgVIssYD3BglOQtkTZnWr2a/eD9SwGYP2EPD0AatRO14a0iqpWNe5GG4NjAWuhG67CjyGsFWlVIbFQL2a9S98mrRX0Xr9gQc4OYZcQ939Pn7FSC3va/R/eaAXZ4vLD4xYkA1aFGf7w128hlHinWEuV1J5pbLGntVHALTry4cGDrI8/MJkew+oG0UnBkjuahlReUPneJTlOmhZWqz1uBLbJKkVfpY33ckJyUYf6HIHe/VwLDG4DfKYDuIoi4zWdoGvOFa/UqmTOn0ATb4IVAFB0GNDiwkKLVhKaZBR3DZQUxY9sRYMDXnCV7YnJCC0Kc1eli424SBFAhnW6n5lpkhGoKn7kDqFKMkout+HVSjlH2L/clj7bDeB1a06a1LsuEccOy2nPFs2ahZQKprDKHDb0D8LOA50MCmff8w0Ya9MpKPZLttrF2he5MxWPdwruMwR8aFo9q3WsE+CI0YU8rWkUqnZeWkGfHysAOter6HlgU6GfgGRjpN5pSsBssplxB/G4=
