sudo: false
language: node_js
node_js:
- 12.8.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
    - libavutil-dev
os:
- osx
- linux
- windows
env:
- YARN_GPG=no # otherwise windows build hangs
before_install:
- if [ $TRAVIS_OS_NAME = windows ]; then cinst -y python2; fi
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- yarn prebuild
- if [ $TRAVIS_OS_NAME = windows ]; then yarn prebuild-ia32; fi
- ls $TRAVIS_BUILD_DIR
- ls $TRAVIS_BUILD_DIR/prebuilds/
- ls $TRAVIS_BUILD_DIR/prebuilds/darwin-x64/
- if [ $TRAVIS_OS_NAME = osx ]; then cp "$TRAVIS_BUILD_DIR/lib/libavutil.dylib" "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/";
  install_name_tool -change "/usr/local/lib/libavutil.56.dylib" "@loader_path/libavutil.dylib"
  "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/node-napi.node"; otool -L "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/node-napi.node";
  install_name_tool -change "/usr/local/lib/libavutil.56.dylib" "@loader_path/libavutil.dylib"
  "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/electron-napi.node"; otool -L "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/electron-napi.node";
  fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: 12.8.1
  api_key:
    secure: XZXIe99yofobVgBK3HTa7sm/FVwqFVSdjUGFV10K+TMw8bSjjtYIu9LqnLPmOCAh1FKRKoD5W+D94WjMxhoyfUUSB9mWe1HiWy8rnno0ED7FhRnzM06bQLMcac6YVPiANXR/ihfPxJmhdYX9oy9FPFP0PP/uo5rLlqV766HU8L2V0NGQlVHIGM6omlgDEGRcNq4B0Q4od7sDtSlU5Krf7lMDx+i9ERghU7m613VXC42k6QNeuZjqdoRJlKV9L++o5jZoxUTF6vZRNpCcuj0PyHdRF97EoTG5mvz/4pXGrBsQjV7sYaUnn9v2J7Jh/WZQUlqUdIwg7/y+Blh3O80Aw4l23QxeFYWF9nzISiiqW4i2Azi03npZ/DZtQhNKewnXRzx2JPBsRIvXJLsI2/mnnrDMGeWkgNKWk93ria0izYFBfPGOqJ3lJtEvMuLIpwqQ/+2sQLceAcsCYUtK6eeUC78qRKP/5z3M7Y0mYOoGhdnX02gfct221+zTGgmeL/6EiGsm95VDe5UAbLwsXH80T7IEKRJTF/z4wWRbUCaFgj3JkHqWL/GUC0T1lBo24U4nBxYUtMzPGcU0QqlO6TL2BQaapvQ8o0tXNUqAyEhBC7ErbLbNgAKDS+QOtuCXt1nGJZ3B5qHL7RLTIKWocK3rwuPjLDWjon6dSWqQ+fu3YUQ=
